name: LRS4GAP
version: 0.20
date: 26/10/2017
description: |
    LRS interface for Linear Programming in GAP

authors:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg

maintainers:
    - name: Gábor Péter Nagy
      url: http://www.math.u-szeged.hu/~nagyg

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nagygp.github.io/LRS4GAP/
readme: README.md
packageinfo: https://nagygp.github.io/LRS4GAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/LRS4GAP/releases/download/v0.20/LRS4GAP-0.20.tar.gz

abstract: |
    

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
