name: GLRS4GAP
version: 0.1
date: 23/10/2017
description: |
    GLRS interface for Linear Programming in GAP

authors:
    - name: Gabor Peter Nagy
      url: www.math.u-szeged.hu/~nagyg

maintainers:
    - name: Gabor Peter Nagy
      url: www.math.u-szeged.hu/~nagyg

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"

www: https://nagygp.github.io/GLRS4GAP/
readme: README.md
packageinfo: https://nagygp.github.io/GLRS4GAP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/nagygp/GLRS4GAP/releases/download/v0.1/GLRS4GAP-0.1.tar.gz

abstract: |
    

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
